### ISSUE TITLE
Observers can crash the cell

### ISSUE THREAD

**Issue by keyboardsamurai** [adad184/MMParallaxCell#2]
The component registers as an observer for contentOffset and may get added removed in a manner that results in a reproducible crash.

What fixed the crash as a workaround for me is to wrap this around addObserver in the willMoveToSuperview method

```
if ( self.parentTableView )
{
    NSLog(@"Added observer %@", self);
    @try {
        [self.parentTableView removeObserver:self forKeyPath:@"contentOffset" context:nil];
        [self.parentTableView addObserver:self forKeyPath:@"contentOffset" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld context:nil];
    }
    @catch (NSException *exception) {

    }
}
```

I think the add and remove cycle of the observer is broken though and this might not be the safest thing to do.

**Comment by adad184** [comment]
nice suggestion, I'll fix it tommorow when I'm back to work :)

thx

and I rechecked my code then notice that I did not set `self.parentTableView` to nil before I search the new parentTableView.

**Comment by keyboardsamurai** [comment]
Yes, if you could take a look that would be awesome. I just realized removing and adding the observer as I do in the code above makes the crash disappear, but also seems to stop the parallax scroll from happening so my workaround is not that great ;)

**Comment by adad184** [comment]
maybe the problem is addObserver never be called because removeObserver throw the exception.

what's your code which cause the crash?    maybe the problem is the way of usage.

**Comment by keyboardsamurai** [comment]
Yes, you are right. That is exactly what was happening. On the occasions where removeObserver crashes, of course addObserver isn't called. I'll see if I can put together a testcase to play with, so I can demonstrate the initial crashing behavior.

**Comment by keyboardsamurai** [comment]
I finally got around to write a small testcase that reliably crashes for me in iOS 8.4 https://github.com/keyboardsamurai/MMParallaxTest

**Comment by adad184** [comment]
well..   i know what's the problem.  You used wrongly the tableview delegate.

``` objc
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    MMParallaxCell* cell = [MMParallaxCell new];
    cell.parallaxImage.image = [UIImage imageNamed:@"default1"];
    return cell;
}
```

it's not right, you should reuse the cell like what i've done in the demo 

``` objc

    static NSString* cellIdentifier = @"CellIdentifier";
    MMParallaxCell* cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
    if (cell == nil)
    {
        cell = [[MMParallaxCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellIdentifier];
        cell.parallaxRatio = 1.2f;
    }
```

please check the official document: 
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableView_Class/index.html#//apple_ref/occ/instm/UITableView/dequeueReusableCellWithIdentifier:forIndexPath:

**Comment by keyboardsamurai** [comment]
That was my first thought initially too, but after some testing I found that it just makes the crash less likely. That is probably because the cells are not trashed and recreated as much when they are being reused. I was intentionally dropping the reference in that sample to make the issue more apparent. Unless I am missing something very important, there should be no reason for the code to crash, right?

**Comment by keyboardsamurai** [comment]
I updated the sample to include a UINavigationController that opens a new ViewController when you tap on a cell. If you tap a couple of times, go back a couple of times and scroll up and down aggressively you will eventually see the bug occurring again. It's now just comparatively hard to reproduce.

**Comment by adad184** [comment]
may it be the memory issue?  could you please upload the full project files?
I can't build the project because some files was missed. (like Pod project)

**Comment by keyboardsamurai** [comment]
Pushed all code again and tested it, project should work if you download the zip. Make sure you open the .xcworkspace file, not .xcodeproj. It's a memory issue at some level, yes, but it seems to be caused by an odd add/remove cycle of the observers.

**Comment by adad184** [comment]
in your demo, I scrolled top to bottom several times, and push & pop several times too, but it looks so fine & never crashed :) 

weird.

**Comment by keyboardsamurai** [comment]
If you want to provoke the crash with minimal effort, just get rid of the dequeueing and recreate the cells each time they are called. It's the same thing. But I made it work with the dequeueing code as well - you just have to be really aggressive while scrolling and tapping. See this video I made when running in Appcode, it shows you where the crash happens in the debug window. https://www.dropbox.com/s/i1jwalxi7qzs2sj/mmparallax-crash.mov?dl=0

**Comment by adad184** [comment]
ok,  could you please test the code below?

``` objc
- (void)willMoveToSuperview:(UIView *)newSuperview
{
    [super willMoveToSuperview:newSuperview];


    [self safeRemoveObserver];

    UIView *v = newSuperview;
    while ( v )
    {
        if ( [v isKindOfClass:[UITableView class]] )
        {
            self.parentTableView = (UITableView*)v;
            break;
        }
        v = v.superview;
    }
    [self safeAddObserver];
}

- (void)removeFromSuperview
{
    [super removeFromSuperview];

    [self safeRemoveObserver];
}

- (void)safeAddObserver
{
    if ( self.parentTableView )
    {
        @try {
            [self.parentTableView addObserver:self forKeyPath:@"contentOffset" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld context:nil];
        }
        @catch(NSException *exception) {

        }
    }
}

- (void)safeRemoveObserver
{
    if ( self.parentTableView )
    {
        @try {
            [self.parentTableView removeObserver:self forKeyPath:@"contentOffset" context:nil];
        }
        @catch (NSException *exception) {

        }
        @finally {
            self.parentTableView = nil;
        }
    }
}

- (void)dealloc
{
    [self safeRemoveObserver];
}
```

**Comment by keyboardsamurai** [comment]
That did the trick. Neither dequeueing nor recreating the cell will crash it now, no matter how hard I try. Nice work. Thank you for helping me chase down that bug :+1:

**Comment by adad184** [comment]
thank you for your attention to this project :)

I will update the code a bit later

**Comment by adad184** [comment]
pod is updated to "1.2", please update the pod the see it. :)

**Comment by keyboardsamurai** [comment]
Works perfectly. Thank you again!
